ZTP additions

diff --git a/src/consolepi-commands/consolepi-ztp b/src/consolepi-commands/consolepi-ztp
--- a/src/consolepi-commands/consolepi-ztp
+++ b/src/consolepi-commands/consolepi-ztp
@@ -3,6 +3,12 @@
 DEBUG=${DEBUG:-false}  # export DEBUG=true prior to running to enable.  Currently just prevents deletion of states file
 state_file=/tmp/pre-ztp-states
 
+print_msgs() {
+    for msg in "${@}"; do
+        echo -e "$msg" |  cut -d']' -f 3 | sed -e 's/^[[:space:]]*//'
+    done
+}
+
 ztp_check_old_dnsmasq() {
     # ConsolePi-ztp utilizes the newer interface speciffic dhcp if they are using the older method using dnsmasq.conf stop
     if head -1 /etc/dnsmasq.conf 2>/dev/null | grep -q 'ConsolePi installer' ; then
@@ -42,7 +48,9 @@ ztp_do_imports() {
 ztp_prep() {
     process="PREP ZTP"
 
-    user_input true "Start DHCP for ZTP Now"
+    systemctl is_active consolepi-wired-dhcp >/dev/null && word=Restart || word=Start
+    [[ "$1" == "y" ]] && result=true ||
+        user_input true "$word DHCP for ZTP Now"
     if $result; then
 
         [ -f "$state_file" ] && . "${state_file}"
@@ -51,21 +59,25 @@ ztp_prep() {
         if which in.tftpd >/dev/null 2>&1; then
             if [[ "$(systemctl is-active tftpd-hpa 2>/dev/null)" == "active" ]]; then
                 echo "tftp_hpa_active=${tftp_hpa_active:-true}" >> $state_file
-                logit "Stopping tftpd-hpa ZTP utilizes dnsmasq tftpd"
+                print_msgs "$(logit "Stopping tftpd-hpa ZTP utilizes dnsmasq tftpd")"
                 sudo systemctl stop tftpd-hpa 2>/dev/null
+            else
+                echo "tftp_hpa_active=${tftp_hpa_active:-false}" >> $state_file
             fi
 
             if [[ "$(systemctl is-enabled tftpd-hpa 2>/dev/null)" == "enabled" ]]; then
                 echo "tftp_hpa_enabled=${tftp_hpa_enabled:-true}" >> $state_file
-                logit "Disabling tftpd-hpa ZTP utilizes dnsmasq tftpd"
+                print_msgs "$(logit "Disabling tftpd-hpa ZTP utilizes dnsmasq tftpd")"
                 sudo systemctl disable tftpd-hpa 2>/dev/null
+            else
+                echo "tftp_hpa_enabled=${tftp_hpa_enabled:-false}" >> $state_file
             fi
         fi
 
         if ! $wired_dhcp; then
             echo "wired_dhcp=false" >> $state_file
             wired_dhcp=true
-            logit "wired-dhcp Enabled in Config"
+            print_msgs "$(logit "wired-dhcp Enabled in Config")"
         fi
 
         if [ -z "$wired_ip" ]; then
@@ -80,18 +92,27 @@ ztp_prep() {
         gen_dhcpcd_conf
         return 0
     else
+        echo
+        msg=()
         if $wired_dhcp; then
+            _word=restart
             _tftp=$(sudo netstat -lnpu | grep "$eth_ip:69\s.*" | awk '{print $6}')
             _tftp_proc=$(echo "$_tftp" | cut -d'/' -f2)
             _tftp_pid=$(echo "$_tftp" | cut -d'/' -f1)
             [ -z "$_tftp" ] && warn=false || warn=true
             [[ $_tftp_proc =~ "dnsmasq" ]] && ps aux | grep -v grep |grep -q "$_tftp_pid.*ConsolePi.*wired-dhcp.*" && warn=false
             if $warn; then
-                logit "Warning wired-dhcp was already enabled but $_tftp_proc is using the tftp port" "WARNING"
-                logit "This will likely cause a conflict when the ConsolePi wired-dhcp config for ZTP tries to start"
+                msg+=("$(logit "Warning wired-dhcp was already enabled but $_tftp_proc is using the tftp port" "WARNING")")
+                msg+=("$(logit "This will likely cause a conflict when the ConsolePi wired-dhcp config for ZTP tries to start")")
             fi
+        else
+            _word=start
         fi
-        return 1
+        msg+=("\nUse 'consolepi-ztp -start' to $_word DHCP with ztp configuration")
+        $warn && msg+=("  This will handle temporarily stopping $_tftp_proc to prevent conflict with the dnsmasq tftp process")
+        print_msgs "${msg[@]}"
+        echo
+        $warn && return 1 || return 0
     fi
 }
 
@@ -107,23 +128,29 @@ check_ssh() {
     $result && return 0 || return 1
 }
 
-start_ztp() {
+ztp_start   () {
     echo -e "\nStarting DHCP configured for ZTP on eth0..."
     if [[ "$eth_ip" != "$wired_ip" ]]; then
         echo -e "Release ~ Renew dhcp on eth0: DHCP Server for ZTP will start when eth0 falls-back to static"
         echo -e "${_bold}NOTE: ${_cyan}As a safety precation the DHCP server will only start if eth0 fails to get an IP from DHCP as a client${_norm}"
         sudo dhcpcd -k eth0 >/dev/null && sudo dhcpcd -n eth0 >/dev/null
-    else
-        if [[ "$(systemctl is-active consolepi-wired-dhcp)" != "active" ]]; then
-            sudo systemctl daemon-reload && sudo systemctl start consolepi-wired-dhcp &&
-            echo -e "\n${_bold}dhcp/ztp is now running waiting for devices to deploy${_norm}\n"
-        else
-            sudo systemctl daemon-reload && sudo systemctl restart consolepi-wired-dhcp &&
-            echo -e "\n${_bold}dhcp/ztp is now running waiting for devices to deploy${_norm}\n"
-        fi
     fi
-    echo "Use 'consolepi-logs -f' to monitor progress"
-    echo -e "To see pcaps for DHCP/TFTP you can also use 'sudo tcpdump -vnes0 -i eth0 port 67 or port 68 or tftp'\n"
+
+    if [[ "$(systemctl is-active consolepi-wired-dhcp)" != "active" ]]; then
+        sudo systemctl daemon-reload && sudo systemctl start consolepi-wired-dhcp &&
+        echo -e "\n${_bold}dhcp/ztp is now running waiting for devices to deploy${_norm}\n"
+    else
+        sudo systemctl daemon-reload && sudo systemctl restart consolepi-wired-dhcp &&
+        echo -e "\n${_bold}dhcp/ztp is now running waiting for devices to deploy${_norm}\n"
+    fi
+
+    # echo -e "To see pcaps for DHCP/TFTP you can also use 'sudo tcpdump -vnes0 -i eth0 port 67 or port 68 or tftp'\n"
+    echo
+    echo -e "Re-Run 'consolepi-ztp' to reset ZTP/dhcp configuration (start-over, fresh run)"
+    echo -e "Use 'consolepi-ztp -c' to rebuild cfg files based on template without resetting DHCP configuration"
+    echo -e "Use 'consolepi-ztp -show' to to display the current ZTP/dhcp configuration"
+    echo -e "Use 'consolepi-ztp -end' to disable ztp and restore pre-ztp state.\n"
+    echo -e "Use 'consolepi-logs -f' to monitor progress or 'consolepi-ztp -watch' for split screen logs/pcaps (DHCP & tftp)\n"
 }
 
 ztp_end(){
@@ -191,35 +218,122 @@ ztp_end(){
     return 0
 }
 
+is_active() {
+    [[ ! "$1" =~ ".service" ]] && _s=$1.service || _s=$1
+    _t=$(systemctl list-unit-files "$_s")
+    if [[ "$_t" =~ "$_s" ]]; then
+        systemctl is-active "$_s" > /dev/null &&
+            _state="${_green}active${_norm}" ||
+            _state="${_lred}inactive${_norm}"
+            echo -e "${_state}"
+    else
+        echo -e "${_lred}not${_norm} installed"
+    fi
+}
+
+ztp_show() {
+    _cr=false
+    _good=${_green}+${_norm}
+    _bad=${_lred}-${_norm}
+    for _file in "$state_file" \
+                 /etc/ConsolePi/dnsmasq.d/wired-dhcp/wired-dhcp.conf \
+                 /etc/ConsolePi/dnsmasq.d/wired-dhcp/ztp.conf \
+                 /etc/ConsolePi/dnsmasq.d/wired-dhcp/ztp-opts/ztp-opts.conf \
+                 /etc/ConsolePi/dnsmasq.d/wired-dhcp/ztp-hosts/ztp-hosts.conf
+        do
+            if [ -f "$_file" ]; then
+                echo -e "\n $_good ---- Contents of $_file ---- " && cat "$_file" && echo -e " ---\n"
+            else
+                ! $_cr && echo && _cr=true
+                ( [[ $_file =~ "ztp.conf" ]] || [[ $_file =~ "wired-dchp.conf" ]] ) &&
+                    msg="${_lred}ZTP does not appear to be ready,${_norm} run ${_cyan}'consolepi-ztp'${_norm} (with no arguments)"
+                echo -e " $_bad $_file does not exist"
+            fi
+        done
+    # echo -e "\nWired DHCP is currently $(systemctl is-active consolepi-wired-dhcp.service)"
+    systemctl is-active consolepi-wired-dhcp.service > /dev/null && tik=$_good || tik=$_bad
+    echo -e "\n $tik Wired DHCP is $(is_active consolepi-wired-dhcp.service)"
+
+    _tftp=$(sudo netstat -lnpu | grep "$eth_ip:69\s.*" | awk '{print $6}')
+    if [[ $_tftp =~ "dnsmasq" ]]; then
+        echo -e " $_good dnsmasq tftp process is listening on wired interface"
+    elif systemctl is-active tftpd-hpa >/dev/null; then
+        echo -e " $_bad tftpd-hpa is $(is_active tftpd-hpa)"
+        echo -e "    tftpd-hpa is currently running which will interfere with the ConsolePi ZTP orchistrator"
+        echo -e "    'consolepi-ztp' will stop tftpd-hpa when DHCP is started\n"
+    else
+        echo -e " $_bad dnsmasq tftp process is ${_lred}not${_norm} listening on wired interface"
+        echo -e "   This is required for ConsolePi ZTP orchestration"
+    fi
+
+    [ ! -z "$msg" ] && echo -e "$msg"
+    echo
+}
+
+ztp_help() {
+    echo
+    echo "USAGE: consolepi-ztp [OPTIONS]"
+    echo "  No arguments: Generate Configuration templates based on config, and prep DHCP for ZTP"
+    echo "  -start|-S:  Start DHCP for ZTP (only necessary if you chose not to start DHCP on initial run of consolepi-ztp)"
+    echo "  -end|-e:    Reset ConsolePi to pre-ztp state (DHCP back to orig state, revert back to tftpd-hpa if installed...)"
+    echo "  -show|-s:   Show current DHCP configuration"
+    echo "  -j2|-c:     Generate configuration templates only, do not prep DHCP for ZTP"
+    echo "  -watch|-w:  Launch byobu(tmux) session with logs and pcap to monitor ZTP progress"
+    echo "              CTRL-C then exit each pane to leave the tmux session or use byobu or tmux sequences"
+    echo
+}
+
 ztp_process_args() {
     local args=()
     while (( "$#" )); do
         case "$1" in
-            *end)
+            *end|-e)
                 ztp_end "${@}" && exit 0 || exit 1
-                shift  # placeholder in event more is added
+                ;;
+            *show|-s)
+                ztp_show "${@}" && exit 0 || exit 1
+                ;;
+            *start|-S)
+                if [ ! -f "/etc/ConsolePi/dnsmasq.d/wired-dhcp/ztp.conf" ]; then
+                    echo
+                    echo "Start option is only useful if you chose not to start DHCP right away after the first pass"
+                    echo "ztp configuration for DHCP doesn't appear to be in place.  Please run consolepi-ztp (without args)"
+                    echo
+                    exit 1
+                else
+                    ztp_prep y && check_ssh && ztp_start && exit 0 || exit 1
+                fi
+                ;;
+            *j2|-c)  # gen/re-gen configurations only don't reset dhcp sequence
+                consolepi-py /etc/ConsolePi/src/ztp.py nodhcp && exit 0 || exit 1
+                ;;
+            *watch|-w)
+                ${src_dir}byobu-ztp-watcher.sh ; exit $?
+                ;;
+            *help)
+                ztp_help && exit 0
                 ;;
             *)
-                local args+=("$1")
-                shift
+                echo -e "\n${_lred}Unrecognized Option $1${_norm}"
+                ztp_help && exit 1
                 ;;
         esac
     done
-    set -- "${args[@]}"
 }
 
 ztp_main() {
-    ztp_check_old_dnsmasq || exit 1                                             # Check They don't have old dnsmasq setup
-    ztp_do_imports || ( echo "Failed to import common functions" && exit 1 )    # import functions
-    ztp_process_args "${@}"                                                     # collect command line args
-    consolepi-py /etc/ConsolePi/src/ztp.py ${@} &&                              # Launch ztp script to parse config and configure ztp files/templates
-    ztp_prep &&                                                                 # shutdown any conflicting services save states for restore after
-    check_ssh &&                                                                # warn if they are on an ssh session and start_ztp would result in a loss in connection
-    start_ztp                                                                   # Trigger Start of consolepi-wired-dhcp.service (eth0 specific instance)
+    ztp_check_old_dnsmasq || exit 1                                                 # Check They don't have old dnsmasq setup
+    ztp_do_imports "${@}" || ( echo "Failed to import common functions" && exit 1 ) # import functions
+    ztp_process_args "${@}"                                                         # process command line args
+    consolepi-py /etc/ConsolePi/src/ztp.py ${@} &&                                  # Launch ztp script to parse config and configure ztp files/templates
+    ztp_prep &&                                                                     # shutdown any conflicting services save states for restore after
+    check_ssh &&                                                                    # warn if they are on an ssh session and ztp_start would result in a loss in connection
+    ztp_start                                                                       # Trigger Start of consolepi-wired-dhcp.service (eth0 specific instance)
 }
 
 case "$0" in
     *consolepi-ztp)
         ztp_main "${@}"
+        shift
         ;;
 esac
