Continue testing new local dev stuff

diff --git a/src/consolepi-commands/consolepi-sync b/src/consolepi-commands/consolepi-sync
--- a/src/consolepi-commands/consolepi-sync
+++ b/src/consolepi-commands/consolepi-sync
@@ -42,7 +42,7 @@ user_input_bool() {
 }
 
 do_perms() {
-    echo " -- Verify Permissions"
+    echo -e "\n -- Verify Permissions"
     dots "verify ConsolePi dir exists"
     [ -d $consolepi_dir ] ; do_error $?
 
@@ -71,14 +71,16 @@ do_git_pull() {
 
 do_loc_pull() {
   if [[ -f $loc_pull_file ]] ; then
-    echo " -- Performing local only Pull"
+    echo -e "\n -- Performing local only Pull"
     orig_IFS=$IFS
     IFS=$'\r\n' GLOBIGNORE='*' command eval  "sync_files=(\$(cat ${loc_pull_file}))"
     for f in "${sync_files[@]}" ; do
       pushd ${f%/*} >/dev/null
-      sftp $rem_user@$loc_pull_host:${consolepi_dir}/${f} ; local rc=$?
+      dots "GET ${f##/*}"
+      sftp $rem_user@$loc_pull_host:${consolepi_dir}/${f} >/dev/null 2>&1 ; local rc=$?
       popd >/dev/null
-      [[ $rc -gt 0 ]] && echo "Error returned - sftp $rem_user@$loc_pull_host:${consolepi_dir}/${f} exitting..." && exit 1
+      do_error $rc
+      # [[ $rc -gt 0 ]] && echo "Error returned - sftp $rem_user@$loc_pull_host:${consolepi_dir}/${f} exitting..." && exit 1
     done
     IFS=$orig_IFS
   else
@@ -88,7 +90,7 @@ do_loc_pull() {
 
 do_stash_local() {
   if [[ -f $loc_pull_file ]] ; then
-    echo " -- Stashing files previously pulled manually"
+    echo -e "\n -- Stashing files previously pulled manually"
     orig_IFS=$IFS
     IFS=$'\r\n' GLOBIGNORE='*' command eval  "sync_files=(\$(cat ${loc_pull_file}))"
     for f in "${sync_files[@]}" ; do
@@ -113,7 +115,7 @@ do_pip_upgrade() {
   [ $py3ver -ge 6 ] && req_file="/etc/ConsolePi/installer/requirements.txt" ||
                       req_file="/etc/ConsolePi/installer/requirements-legacy.txt"
 
-  echo  " -- pip install/upgrade ConsolePi requirements - This can take some time."
+  echo -e "\n -- pip install/upgrade ConsolePi requirements - This can take some time."
   dots "Upgrade pip"
   sudo /etc/ConsolePi/venv/bin/python3 -m pip install --upgrade pip 1>$log_file 2>&1 ; do_error $?
   dots "Upgrade ConsolePi Dependencies"
