handle another error code being returned by iw in current RaspiOS

diff --git a/src/autohotspotN b/src/autohotspotN
--- a/src/autohotspotN
+++ b/src/autohotspotN
@@ -128,7 +128,7 @@ fi
 
 [[ -z $hotspot ]] && hotspot=true && logit "HotSpot variable not found in ConsolePi Configuration falling back to true (Enabled)" "WARNING"
 ! $hotspot && logit "ConsolePi Auto HotSpot is disabled in the config but this script was triggered, Disable the systemd file" "WARNING" &&
-    logit "Auto HotSpot script will now exit" && exit 0
+    logit "ConsolePi Auto HotSpot exiting" && exit 0
 
 ifaces=$(ip -br link show | grep -v lo | awk '{printf $1 " "}')
 # -- get wlan interface from hostapd.conf if found/defined --
@@ -145,15 +145,12 @@ wpassid=$(awk '/ssid="/{ print $0 }' /etc/wpa_supplicant/wpa_supplicant.conf | a
 IFS=","
 ssids=($wpassid)
 IFS=$IFSdef #reset back to defaults
+
 # Number of seconds the script will pause after wifi is enabled before checking to see if it successfully connected.
 [ -z $wlan_wait_time ] && wlan_wait_time=20
 
 
-#Note:If you only want to check for certain SSIDs
-#Remove the # in in front of ssids=('mySSID1'.... below and put a # infront of all four lines above
-# separated by a space, eg ('mySSID1' 'mySSID2')
-#ssids=('mySSID1' 'mySSID2' 'mySSID3')
-
+# TODO add this to overrides
 #Enter the Routers Mac Addresses for hidden SSIDs, seperated by spaces ie
 #( '11:22:33:44:55:66' 'aa:bb:cc:dd:ee:ff' )
 mac=()
@@ -163,7 +160,8 @@ ssidsmac=("${ssids[@]}" "${mac[@]}") #combines ssid and MAC for checking
 get_ssid_details() {
     wlan_ip_addr=$(wpa_cli -i $wifidev status | grep ip_address | cut -d'=' -f2)
     if which iwgetid >/dev/null ; then
-        logit "$1 connected to ${_green}$(iwgetid $wifidev -r)${_norm} with IP ${wlan_ip_addr} AP $(iwgetid $wifidev -a | awk '{print $4}') using $(iwgetid $wifidev -f|awk '{print $2}')"
+        local _log="$1 connected to ${_green}$(iwgetid $wifidev -r)${_norm} with IP ${wlan_ip_addr} AP $(iwgetid $wifidev -a | awk '{print $4}') using $(iwgetid $wifidev -f|awk '{print $2}')"
+        [ ! -z "$2" ] && logit "${_log} Time to Connect ${_cyan}$2 sec${_norm}" || logit "${_log}"
     else
         logit "$HOSTNAME is connected to a valid SSID"
     fi
@@ -214,17 +212,31 @@ KillHotspot() {
 }
 
 ChkWifiUp() {
-    logit "Checking WiFi connection ok"
-    logit "pausing $wlan_wait_time seconds to allow wpa_supplicant time to connect"
-    sleep $wlan_wait_time #give time for connection to be completed to router
+    logit "Checking that WiFi connection is OK"
+    # logit "pausing $wlan_wait_time seconds to allow wpa_supplicant time to connect"
+    # sleep $wlan_wait_time #give time for connection to be completed to router
+
+    # Wait for connection and ip on interface
+    start_time=$(date +"%s")
+    _bumped=false
+    while ! wpa_cli -i "$wifidev" status | grep -q 'ip_address'; do
+        sleep 3
+        # if wlan is associated give it a little more time to complete AuthN
+        ! $_bumped && wpa_cli -i "$wifidev" status | grep -q 'ASSOCIAT' && ((wlan_wait_time+=10)) && _bumped=true
+        [[ $(date +"%s") > $((start_time + wlan_wait_time)) ]] && break
+    done
+    connect_time=$(($(date +"%s") - start_time))
+
+
     if ! wpa_cli -i "$wifidev" status | grep 'ip_address' >/dev/null 2>&1; then
         logit 'Wifi failed to connect, falling back to Hotspot.' "WARNING"
         wpa_cli terminate "$wifidev" >/dev/null 2>&1
         createAdHocNetwork
     else
-        get_ssid_details Now
+        get_ssid_details Now $connect_time
     fi
 }
+
 
 ChkWiredState() {
     if [[ "$ifaces" =~ "$ethdev" ]]; then
@@ -282,6 +294,9 @@ ChkWiredState() {
 FindSSID() {
     #Check to see what SSID's and MAC addresses are in range
     ssidChk=('NoSSid')
+    # used to determine if we just booted, if so double loop counter
+    uptime=$(sudo cat /proc/uptime | awk '{print $1}') && uptime=$(echo ${uptime//.*/})
+    # uptime on initial hit on Pi4 was consistently 14 seconds
     i=0; j=1
     until [ $i -eq 1 ] ; do # wait for wifi if busy, usb wifi is slower.
         ssidreply=$((iw dev "$wifidev" scan ap-force | egrep "^BSS|SSID:") 2>&1) >/dev/null 2>&1
@@ -294,27 +309,31 @@ FindSSID() {
             logit "SSid's in range: $ssidreply" "DEBUG"
         fi
 
-        (($j > 1)) && logit "Device Available Check try $j"
-        if (($j >= 10)); then #if busy 10 times goto hotspot
-            logit "Device busy or unavailable 10 times, going to Hotspot"
+        (($j > 1)) # && logit "Device Available Check try $j"
+        if (($j >= 10)) && (($uptime > 60)); then #if busy 10 times goto hotspot unless we just booted up then give it a min
+            logit "Device busy or unavailable $j times, enabling Hotspot"
             ssidreply=""
             i=1
-        elif echo "$ssidreply" | grep "No such device (-19)" >/dev/null 2>&1; then
+        elif echo "$ssidreply" | grep -q "No such device (-19)"; then  # >/dev/null 2>&1; then
             logit "No Device Reported, try $j"
             NoDevice
-        elif echo "$ssidreply" | grep "Network is down (-100)" >/dev/null 2>&1 ; then
+        elif echo "$ssidreply" | grep -q  "Network is down (-100)"; then  # >/dev/null 2>&1 ; then
             logit "Network Not available, trying again $j"
             j=$((j + 1))
             sleep 2
-        elif echo "$ssidreply" | grep "Read-only file system (-30)" >/dev/null 2>&1 ; then
+        elif echo "$ssidreply" | grep -q "Read-only file system (-30)"; then  # >/dev/null 2>&1 ; then
             logit "Temporary Read only file system, trying again"
             j=$((j + 1))
             sleep 2
-        elif echo "$ssidreply" | grep "Invalid exchange (-52)" >/dev/null 2>&1 ; then
+        elif echo "$ssidreply" | grep -q "Invalid exchange (-52)"; then  # >/dev/null 2>&1 ; then
             logit "Invalid Exchange ~ Transient Error, trying again"
             j=$((j + 1))
             sleep 2
-        elif ! echo "$ssidreply" | grep "resource busy (-16)"  >/dev/null 2>&1 ; then
+        elif echo "$ssidreply" | grep -q "esource temporarily unavailable "; then  # >/dev/null 2>&1 ; then
+            logit "Resource temporarily unavailable"
+            j=$((j + 1))
+            sleep 2
+        elif ! echo "$ssidreply" | grep -q "esource busy (-16)" ; then  # >/dev/null 2>&1 ; then
             logit "Device Available, checking SSid Results"
             i=1
         else #see if device not busy in 2 seconds
@@ -374,7 +393,9 @@ else #ssid or MAC address not in range
         wpa_cli terminate >/dev/null 2>&1
         ip addr flush "$wifidev"
         ip link set dev "$wifidev" down
-        rm -r /var/run/wpa_supplicant >/dev/null 2>&1
+        _ctrl_if=$(grep "^ctrl_interface" /etc/wpa_supplicant/wpa_supplicant.conf)
+        _ctrl_if=$(echo ${x// GROUP*/} | rev | cut -d= -f 1 | rev)
+        rm -r "$_ctrl_if" >/dev/null 2>&1
         createAdHocNetwork
         exit 0
     else #"No SSID, activating Hotspot"
