re-work to use yaml config file

diff --git a/src/autohotspotN b/src/autohotspotN
--- a/src/autohotspotN
+++ b/src/autohotspotN
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #version 0.95-4-N/HS-I ConsolePi Rev 1.5
 
 #You may share this script on the condition a reference to RaspberryConnect.com 
@@ -11,30 +11,52 @@
 #Other setup required find out more at
 #http://www.raspberryconnect.com
 
-#Slight Modifications for ConsolePi
-#variablelize hotspot IP referenced in createAdHocNetwork
-#import ConsolePi.conf for variable values
-#Add chkWiredState function
-# chkWiredState modifies the dnsmasq DHCP server configuration
-# So the hotspot will provide an IP with no default gateway
-# if the wired interface is down.  It also cheks the domain
-# provided to the wired interface via DHCP and provides that
-# same domain to hotspot clients.
+# -- Modified for ConsolePi --
+# -- variablelize hotspot IP referenced in createAdHocNetwork
+# -- import ConsolePi configuration (ConsolePi.yaml)
+# -- Add chkWiredState function
+#      chkWiredState modifies the dnsmasq DHCP server configuration
+#      So the hotspot will provide an IP with no default gateway
+#      if the wired interface is down.  It also cheks the domain
+#      provided to the wired interface via DHCP and provides that
+#      same domain to hotspot clients.
 
-# The default-gateway bit is done so you can connect
-# in a dual nic setup and not corrupt your routing table
-# with an invalid route
+# -- The default-gateway bit is done so you can connect
+# -- in a dual nic setup and not corrupt your routing table
+# -- with an invalid route
 
-# Passing on the domain the the hostpot users is primarily done
-# for auto-openvpn which will not initiate a connection if the
-# ConsolePi is connected to your home network.  So it's primarily
-# for me during dev to prevent openvpn from starting while I'm testing
-# stuff i.e. ConsolePi connected to ConsolePi
+# -- Passing on the domain the the hostpot uses is primarily done
+# -- for auto-openvpn which will not initiate a connection if the
+# -- ConsolePi is connected to your home network.  So it's primarily
+# -- for me during dev to prevent openvpn from starting while I'm testing
+# -- stuff i.e. ConsolePi connected to ConsolePi
 
-# Supported override variables (define the variable in ConsolePi.conf to override with different value)
-# wlan_wait_time: The amount of time the script waits for connection to an SSID before reverting to hotspot
+# Supported override variables (define the variable in ConsolePi.yaml OVERRIDES section)
+# -- None @ this time
 
-[[ -f "/etc/ConsolePi/ConsolePi.conf" ]] && . "/etc/ConsolePi/ConsolePi.conf" || wlan_ip=10.99.99.1
+# -- // extract wlan_ip and hotspot variables from config \\ --
+cfg_file_yaml="/etc/ConsolePi/ConsolePi.yaml"
+cfg_file_conf="/etc/ConsolePi/ConsolePi.conf"
+if [[ -f $cfg_file_yaml ]] ; then
+    wlan_ip=$(grep wlan_ip: $cfg_file_yaml | cut -d : -f 2 | cut -d' ' -f 2)
+    wlan_ip="${wlan_ip//\"/}"
+    hotspot=$(grep HotSpot: $cfg_file_yaml | cut -d : -f 2 | cut -d' ' -f 2)
+    hotspot="${hotspot//\"/}"
+elif [[ -f $cfg_file_conf ]] ; then
+    . $cfg_file_conf
+fi
+if [[ -z $wlan_ip ]] ; then
+    echo "Unable to collect HotSpot IP from ConsolePi.yaml"
+    if [[ -f "/etc/dnsmasq.conf" ]] ; then
+        wlan_pfx=$(grep -q wlan0 /etc/dnsmasq.conf && grep dhcp-range= /etc/dnsmasq.conf | cut -d = -f 2 | cut -d . -f 1-3)
+        [[ ! -z $wlan_pfx ]] && wlan_ip="${wlan_pfx}.1" && echo "Guessed HotSpot IP based on dnsmasq.conf ($wlan_ip)" ||
+            ( echo "Unable to Guess HotSpot IP based on dnsmasq.conf Giving Up" && exit 1 )
+    fi
+fi
+
+[[ -z $hotspot ]] && hotspot=true && echo "HotSpot variable not found in ConsolePi Configuration falling back to true (Enabled)"
+! $hotspot && echo "ConsolePi Auto HotSpot is disabled in the config but this script was triggered, Disable the systemd file" && 
+    echo "Auto HotSpot script will now exit" && exit 0
 
 wifidev="wlan0" #device name to use. Default is wlan0.
 ethdev="eth0" #Ethernet port to use with IP tables
@@ -86,7 +108,6 @@ createAdHocNetwork()
     ip link set dev "$wifidev" up
     debug=`ip addr show dev wlan0 | grep 'inet '| cut -d: -f2 |cut -d/ -f1| awk '{ print $2}'`
 	echo "${wifidev} is up with ip: ${debug}"
-    # logger -t autohotspot $wifidev is up with ip: $debug
     dhcpcd -k "$wifidev" >/dev/null 2>&1
     iptables -t nat -A POSTROUTING -o "$ethdev" -j MASQUERADE
     iptables -A FORWARD -i "$ethdev" -o "$wifidev" -m state --state RELATED,ESTABLISHED -j ACCEPT
