build own custom logit function - remove sourcing of common funcs

diff --git a/src/autohotspotN b/src/autohotspotN
--- a/src/autohotspotN
+++ b/src/autohotspotN
@@ -40,26 +40,48 @@ common_funcs="/etc/ConsolePi/installer/common.sh"
 cfg_file_yaml="/etc/ConsolePi/ConsolePi.yaml"
 cfg_file_conf="/etc/ConsolePi/ConsolePi.conf"  # legacy config support should not be used
 DEBUG=false
-
-# -- source ConsolePi common functions for logit function which tees output to log_file --
+log_file="/var/log/ConsolePi/consolepi.log"
 process="AutoHotSpot"
-if [[ ! -f  $common_funcs ]] || ! . $common_funcs ; then
-    echo "Unable to import common functions"
-    # -- fallback if common_funcs fails to import --
-    logit() {
-        echo "$@"
-    }
+# -- Terminal coloring --
+_norm='\e[0m'
+_bold='\033[1;32m'
+_blink='\e[5m'
+_red='\e[31m'
+_blue='\e[34m'
+_lred='\e[91m'
+_yellow='\e[33;1m'
+_green='\e[32m'
+logit() {
+    # Logging Function: logit <message|string> [<status|string>]
+    # usage:
+    #   process="AutoHotSpot"  # Define prior to calling or defaults to UNDEFINED
+    #   logit "building package" <"WARNING">
+    # NOTE: Sending a status of "ERROR" results in the script exiting
+    #       default status is INFO if none provided.
+    [ -z "$process" ] && process="UNDEFINED"
+    message=$1                                      # 1st arg = the log message
+    [ -z "${2}" ] && status="INFO" && c_status="INFO" || status=${2^^} # to upper
+    fatal=false                                     # fatal is determined by status. default to false.  true if status = ERROR
+    if [[ "${status}" == "ERROR" ]]; then
+        fatal=true
+        c_status="${_red}${status}${_norm}"
+    elif [[ ! "${status}" == "INFO" ]]; then
+        c_status="${_yellow}${status}${_norm}"
+        [[ "${status}" == "WARNING" ]]
+    fi
 
-    # -- Terminal coloring --
-    _norm='\e[0m'
-    _bold='\033[1;32m'
-    _blink='\e[5m'
-    _red='\e[31m'
-    _blue='\e[34m'
-    _lred='\e[91m'
-    _yellow='\e[33;1m'
-    _green='\e[32m'
-fi
+    # -- Log to log-file --
+    echo -e "$(date +"%b %d %T") [${status}][${process}] ${message}" >> $log_file
+
+    # -- Any warning/errors log to syslog as well --
+    if [[ ! "${status}" == "INFO" ]] && [[ ! "${status}" == "DEBUG" ]]; then
+        echo -e "[${status}] ${message}"  # log any errors to syslog as well
+        if $fatal ; then
+            # if status was ERROR which means FATAL then log and exit script
+            echo -e "[${status}] Last Error is fatal, script exiting Please review log ${log_file}" && exit 1
+        fi
+    fi
+}
 
 # -- update path so script can find executables when ran as cron job --
 [[ ! "$PATH" =~ 'sbin' ]]  && PATH="$PATH:/sbin:/usr/sbin"
